[package]
name = "rust-nn-web"
version = "0.1.0"
authors = ["Yashodhan Joshi "]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.63"
ndarray = "0.13.1"
serde = {version="1.0.114",features = ["derive"]}
serde_json = "1.0.0"
rand = "0.7.3"
console_error_panic_hook = { version = "0.1.6", optional = true }
wee_alloc = { version = "0.4.5", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[profile.release]
debug = true
# Tell `rustc` to optimize for small code size.
#opt-level = "s"
